id: I9C2149D0
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-23T05:13:06+00:00'
last_modified: '2022-06-08T09:27:09.500180+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3PD1123
  title: རཏྣ་གླིང་པའི་གཏེར་ཆོས་ཀྱི་ཙཀླི།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    DBC5:
      image_group_id: I3PD1125
      title: ''
      total_pages: 384
      order: 1
      base_file: DBC5.txt
    D123:
      image_group_id: I3PD1126
      title: ''
      total_pages: 816
      order: 2
      base_file: D123.txt
    DD44:
      image_group_id: I3PD1127
      title: ''
      total_pages: 29
      order: 3
      base_file: DD44.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
