id: I9C2149D0
legacy_id: P009217
ocr_import_info:
  bdrc_scan_id: W3PD1123
  source: bdrc
  ocr_info:
    timestamp: '2020-03-23T05:12:49'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-03T17:25:47.102656+00:00'
last_modified: 2022-09-04 01:26:12.385908
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W3PD1123
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW3PD1123
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: རཏྣ་གླིང་པའི་གཏེར་ཆོས་ཀྱི་ཙཀླི།
  author: རཏྣ་གླིང་པ།
statistics:
  ocr_word_mean_confidence_index: 0.7088990403470741
  ocr_word_median_confidence_index: 0.9399999976158142
quality: null
bases:
  I3PD1126:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3PD1126
      total_pages: 816
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I3PD1126.txt
    statistics:
      ocr_word_median_confidence_index: 0.8700000047683716
      ocr_word_mean_confidence_index: 0.6654339151802623
    legacy_id: v002
  I3PD1125:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3PD1125
      total_pages: 384
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I3PD1125.txt
    statistics:
      ocr_word_median_confidence_index: 0.9599999785423279
      ocr_word_mean_confidence_index: 0.7467117275080241
    legacy_id: v001
  I3PD1127:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3PD1127
      total_pages: 29
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I3PD1127.txt
    statistics:
      ocr_word_median_confidence_index: 0.699999988079071
      ocr_word_mean_confidence_index: 0.6485695971619287
    legacy_id: v003
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
